[build]
  # Explicitly install dependencies with npm to ensure devDependencies (like ESLint) are installed
  # Then run build with bun (or npm if bun is not available)
  command = "npm install && bun run build"
  # Alternative: Use npm only if bun is not available on Netlify
  # command = "npm install && npm run build"
  publish = ".next"

[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
